apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackslash-app
  namespace: hackslash
  labels:
    app: hackslash-app
spec:
  selector:
    matchLabels:
      app: hackslash-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hackslash-app
    spec:
      containers:
      - name: hackslash-app
        image: suryanshverma/hackslash-web-app:latest
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hackslash-secret
              key: jwt-secret
        - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
          valueFrom:
            configMapKeyRef:
              name: hackslash-cm
              key: cloudinary-cloud
        - name: NEXT_PUBLIC_CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: hackslash-secret
              key: next-cloudinary-api
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: hackslash-secret
              key:  cloudinary-api
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: hackslash-secret
              key: user
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: hackslash-secret
              key: pass
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: hackslash-cm
              key: mongo-url

        resources:
          requests:
            memory: "2000Mi"
            cpu: "2000m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        ports:
        - containerPort: 3000
