apiVersion: v1
kind: Service
metadata:
  name: hackslash-app
  namespace: hackslash
spec:
  selector:
    app: hackslash-app
  type: NodePort
  ports:
  - name: hackslash-svc
    protocol: TCP
    port: 3000
    targetPort: 3000

