apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: hackslash
  name: mongo-pvc-h
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: Users/surya/OneDrive/Desktop/Team405_Tasks/hackslash-official-site/data
