apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-h
  namespace: hackslash
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce