apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: hackslash
spec:
  selector:
    app: mongodb-depl
  type: ClusterIP
  ports:
  - name: mongo-svc
    protocol: TCP
    port: 27017
    targetPort: 27017
